version: '3.9'
services:
  backend:
#    tty: true
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
#    environment:
#      WAIT_HOSTS: db:3306

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
